apiVersion: v1
kind: Service
metadata:
  name: containerize-sample-svc
spec:
  type: ClusterIP
  selector:
    app: containerize-sample
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
